@startuml

skinparam componentStyle uml2

skinparam component {
BorderColor #grey
BackgroundColor #white
}

skinparam class {
BorderColor #grey
BackgroundColor #white
}

package com.consol.controller {
class ChooseName
class WrongController
}


note "has wrong Name" as WrongPackage #crimson
ChooseName .. WrongPackage

@enduml