@startuml

skinparam componentStyle uml2

skinparam component {
BorderColor #grey
BackgroundColor #white
}

skinparam class {
BorderColor #grey
BackgroundColor #white
}

class Connection <<abstract>>
class HtmlConnection <<concrete>>
class FtpConnection <<concrete>>
class Ssh <<concrete>>

HtmlConnection --|> Connection #green
FtpConnection --|> Connection #green
Ssh --|> Connection #crimson
@enduml