@startuml

skinparam componentStyle uml2

skinparam component {
BorderColor #grey
BackgroundColor #white
}

skinparam class {
BorderColor #grey
BackgroundColor #white
}

package com.myapp.controller {
class OtherControlle
class AnyController
}
package com.myapp.service {
class AnyService
class OtherService
}
package com.myapp.persistence {
class AnyEntity
class OtherEntity
}

OtherControlle --> OtherService #crimson
AnyService --> AnyEntity #crimson
OtherEntity --> OtherControlle #crimson
@enduml