@startuml

skinparam componentStyle uml2

skinparam component {
BorderColor #grey
BackgroundColor #white
}

skinparam class {
BorderColor #grey
BackgroundColor #white
}

package com.myapp.controller {
class OtherController
class AnyController
}
package com.myapp.service {
class AnyService
class OtherService
}
package com.myapp.persistence {
class AnyEntity
class OtherEntity
}

OtherController --> OtherService #crimson
AnyService --> AnyEntity #crimson
OtherEntity --> OtherController #crimson
@enduml