@startuml

skinparam componentStyle uml2
skinparam component {
BorderColor #grey
BackgroundColor #white
}

[service] --[#green]down-->  [persistence]:allowed
[service] --[#crimson]up--> [controller]:forbidden


@enduml